services:
  # api:
  #   build:
  #     context: .
  #     dockerfile: ./server/dockerfile
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #       - redis-server
  #   environment:
  #     - REDIS_URL=redis://redis-server:6379
  redis-server:
    image: redis:7.4-alpine
    container_name: redis-server
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  redis-insight:
    image: redis/redisinsight:latest
    container_name: redis-insight
    ports:
      - "5540:5540"

volumes:
  redis_data:
